"""add audio_s3_key and language to audio_jobs

Revision ID: 8f2945600b71
Revises: 0001_initial
Create Date: 2025-08-07 20:03:06.249986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2945600b71'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_jobs', sa.Column('audio_s3_key', sa.String(length=512), nullable=True))
    op.add_column('audio_jobs', sa.Column('language', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_jobs', 'language')
    op.drop_column('audio_jobs', 'audio_s3_key')
    # ### end Alembic commands ###
