"""init postgres schema

Revision ID: 9c4c9946c423
Revises: 788a7116035b
Create Date: 2026-01-08 20:50:13.226323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4c9946c423'
down_revision = '788a7116035b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_ledger_user_id')

    op.drop_table('usage_ledger')
    with op.batch_alter_table('audio_jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('language_detected',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('duration_seconds',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('original_filename')
        batch_op.drop_column('cost_cents')
        batch_op.drop_column('model_used')
        batch_op.drop_column('error')
        batch_op.drop_column('local_path')
        batch_op.drop_column('audio_s3_key')
        batch_op.drop_column('language_forced')
        batch_op.drop_column('mime_type')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('amount_usd',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verify_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('verify_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plan_tier', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('minute_quota', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('minutes_used', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('paypal_subscription_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cycle_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cycle_end', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_verify_token'), ['verify_token'], unique=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_verify_token'))
        batch_op.drop_column('cycle_end')
        batch_op.drop_column('cycle_start')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('paypal_subscription_id')
        batch_op.drop_column('minutes_used')
        batch_op.drop_column('minute_quota')
        batch_op.drop_column('plan_tier')
        batch_op.drop_column('verify_expires_at')
        batch_op.drop_column('verify_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_active')
        batch_op.drop_column('display_name')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount_usd',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('audio_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('language_forced', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('audio_s3_key', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('local_path', sa.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column('error', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('model_used', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('cost_cents', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('duration_seconds',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('language_detected',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    op.create_table('usage_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('minutes_delta', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), nullable=True),
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('payment_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_usage_ledger_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_token'))

    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
